const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export async function loadOperatingView(transport){const [runtimeStatus,company,capabilities,gaps,plan,activity,observations,findings]=await Promise.all([transport.getRuntimeStatus(),transport.getCompany(),transport.listCapabilities(),transport.listGaps(),transport.getPlan(),transport.listActivity(),transport.listObservations(),transport.listFindings()]);return {runtimeStatus,company,capabilities,gaps,plan,activity,observations,findings}}
export function renderOperatingView(view,{transportName='live',notice=''}={}){
 const capabilities=view.capabilities.map(item=>`<li><strong>${escape(item.name)}</strong><br><span>${escape(title(item.state))}</span></li>`).join('');
 const changes=view.plan?.changes?.map(change=>`<li><strong>+ ${escape(change.resource.category)}.${escape(change.resource.id)}</strong><br>Affects ${escape(change.capability)} — ${escape(change.reason)}<br>Approval: ${escape(change.approval)} · Reversible: ${change.reversible?'yes':'no'}</li>`).join('')||'<li>No current plan</li>';
 const activity=view.activity.map(item=>`<li><strong>${escape(title(item.type.replaceAll('.',' ')))}</strong> <time>${escape(item.time||'')}</time><pre>${escape(JSON.stringify(item.data))}</pre></li>`).join('')||'<li>No activity yet</li>';
 const observations=view.observations.map(item=>`<li>${escape(item.definition.id)}: ${escape(item.execution?.status||'not run')}</li>`).join('')||'<li>No observations</li>';
 const mode=view.runtimeStatus?.mode||transportName,readOnly=mode==='demo'||mode==='fixture';return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>OmniSeed OS — ${escape(view.company.name)}</title><style>${styles}</style><body><header><div><p class="eyebrow">Company as Code</p><h1>OmniSeed OS</h1></div><span class="mode ${escape(mode)}">${escape(title(mode))}${readOnly?' · read-only':''}</span><nav aria-label="Primary"><a href="/found">Found</a><a href="/company">Company</a><a href="/capabilities">Capabilities</a><a href="/plan">Plan</a><a href="/observe">Observe</a><a href="/activity">Activity</a><a href="/eve">Eve</a></nav></header><main>${mode==='demo'?'<aside role="note"><strong>Public demo.</strong> Deterministic example data; mutations are disabled and nothing is persisted. Run locally for live operation.</aside>':''}${notice?`<p role="status">${escape(notice)}</p>`:''}<section id="company"><p class="eyebrow">Company</p><h2>${escape(view.company.name)}</h2><p>${escape(view.company.purpose)}</p><div class="stats"><span><strong>${view.capabilities.length}</strong> capabilities</span><span><strong>${view.capabilities.filter(item=>item.state==='realised').length}</strong> realised</span><span><strong>${view.gaps.length}</strong> gaps</span></div></section><section id="capabilities"><p class="eyebrow">Capabilities</p><h2>What the organisation needs</h2><ul class="cards">${capabilities}</ul></section><section id="plan"><p class="eyebrow">Plan</p><h2>Proposed change</h2><ul class="cards">${changes}</ul>${readOnly?'<p class="muted">Planning and apply are disabled in this read-only environment.</p>':`<form method="post" action="/actions/generate-plan"><button>Generate support-agent plan</button></form>${view.plan?`<form method="post" action="/actions/apply"><button>Approve all development-safe changes and apply</button></form><form method="post" action="/actions/cancel"><button class="secondary">Reject / cancel plan</button></form>`:''}`}</section><section id="observe"><p class="eyebrow">Observe</p><h2>Evidence and findings</h2><ul>${observations}</ul><p>Structured findings: ${view.findings.length}</p></section><section id="activity"><p class="eyebrow">Activity</p><h2>Organisational history</h2><ol>${activity}</ol></section></main><footer>OmniSeed OS · <a href="https://mikeajijola.github.io/omniseedos/">Docs</a></footer></body></html>`;
}
const title=value=>String(value).replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
const styles=`:root{color-scheme:light;--ink:#17201d;--muted:#66716d;--line:#dce3df;--paper:#f7f9f7;--accent:#176b4d}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.55 system-ui,sans-serif}header,main,footer{max-width:1100px;margin:auto;padding:24px}header{display:flex;flex-wrap:wrap;align-items:center;gap:18px}h1,h2,h3,p{margin-top:0}nav{display:flex;flex-wrap:wrap;gap:6px;width:100%}nav a,a{color:var(--accent)}nav a{padding:8px 12px;border-radius:999px;text-decoration:none}nav a:hover,nav a:focus{background:#e4eee9;outline:2px solid transparent}.mode{margin-left:auto;border:1px solid var(--line);border-radius:999px;padding:6px 10px;font-size:.8rem}.mode.demo{background:#fff4ce}.eyebrow{text-transform:uppercase;letter-spacing:.12em;color:var(--muted);font-size:.75rem;font-weight:700;margin-bottom:6px}main{display:grid;gap:18px}section,aside{background:white;border:1px solid var(--line);border-radius:16px;padding:clamp(18px,3vw,30px);box-shadow:0 8px 30px #1c312508}.stats{display:flex;flex-wrap:wrap;gap:12px}.stats span{background:#eef3f0;border-radius:10px;padding:10px 14px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;padding:0;list-style:none}.cards li{border:1px solid var(--line);border-radius:12px;padding:16px}button{background:var(--accent);color:white;border:0;border-radius:9px;padding:11px 15px;font:inherit;font-weight:700;cursor:pointer}.secondary{background:#eef3f0;color:var(--ink)}form{display:inline-block;margin:5px}.muted,time{color:var(--muted)}pre{white-space:pre-wrap;font-size:.75rem}@media(max-width:600px){header,main,footer{padding:16px}header{align-items:flex-start}.mode{margin-left:0}nav{overflow-x:auto;flex-wrap:nowrap}section{border-radius:12px}}`;
