import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import fsp from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {LiveTransport} from '../../lib/omniseed/transport.mjs';import {loadOperatingView,renderOperatingView} from '../../lib/ui/render.mjs';
const runtimeRoot=path.resolve(process.env.OMNISEED_ROOT||'../omniseed');const port=Number(process.env.OMNISEED_TEST_PORT||18787);const baseUrl=`http://127.0.0.1:${port}`;
test('OS receives the complete real OmniSeed lifecycle without calculating state',async()=>{const data=await fsp.mkdtemp(path.join(os.tmpdir(),'omniseedos-live-'));const child=spawn(process.execPath,['packages/runtime/src/server.mjs'],{cwd:runtimeRoot,env:{...process.env,PORT:String(port),OMNISEED_DATA_DIR:data},stdio:['ignore','pipe','pipe']});try{
 await waitForRuntime();const transport=new LiveTransport({baseUrl});let view=await loadOperatingView(transport);assert.equal(view.capabilities.find(item=>item.id==='customer_support').state,'missing');assert.match(renderOperatingView(view),/Customer Support[\s\S]*Missing/);
 const definition=JSON.parse(fs.readFileSync('fixtures/acme-with-support-definition.json'));const plan=await transport.generatePlan(definition);assert.equal(plan.changes[0].resource.id,'support_agent');assert.equal(plan.changes[0].approval,'required');
 await transport.applyPlan({planId:plan.id,approvedChangeIds:plan.changes.map(item=>item.id),authorization:{actorId:'integration-test',permissions:['apply_plan']}});view=await loadOperatingView(transport);assert.equal(view.capabilities.find(item=>item.id==='customer_support').state,'realised');assert.match(renderOperatingView(view),/>2 realised</);assert.match(renderOperatingView(view),/>0 gaps</);
 const types=view.activity.map(item=>item.type);for(const type of ['plan.created','plan.approved','resource.created','state.updated','capability.changed'])assert.ok(types.includes(type),`missing ${type}`);
}finally{child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));await fsp.rm(data,{recursive:true,force:true})}});
async function waitForRuntime(){for(let count=0;count<50;count++){try{if((await fetch(`${baseUrl}/health`)).ok)return}catch{}await new Promise(resolve=>setTimeout(resolve,100))}throw new Error('Runtime did not start')}
