import http from 'node:http';import fs from 'node:fs';import {resolveTransport} from '../lib/omniseed/config.mjs';import {loadOperatingView,renderOperatingView} from '../lib/ui/render.mjs';import {renderFounding} from '../lib/ui/founding.mjs';import {invokeEve} from '../lib/eve/index.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(`../fixtures/${name}`,import.meta.url)));const mode=process.env.OMNISEED_TRANSPORT_MODE||'live';const transport=resolveTransport({mode,runtimeUrl:process.env.OMNISEED_RUNTIME_URL||'http://127.0.0.1:8787',fixture:read('startup.json')});const port=Number(process.env.PORT||3000);
let foundingSessionId=null,notice='';
http.createServer(async(request,response)=>{try{
 if(request.method==='GET'&&request.url==='/found'){const session=foundingSessionId?await transport.getFoundingDraft(foundingSessionId):null,validation=session?await transport.validateFoundingDraft(foundingSessionId):null;response.setHeader('Content-Type','text/html; charset=utf-8');return response.end(renderFounding(session,validation,notice))}
 if(request.method==='POST'&&request.url==='/found/intent'){assertLive();const form=await readForm(request),session=await transport.startFoundingSession('local-founder');foundingSessionId=session.id;await transport.submitFounderIntent(session.id,form.intent);return redirect(response,'/found')}
 if(request.method==='POST'&&request.url==='/found/item'){assertLive();const form=await readForm(request);if(form.action==='accept')await transport.acceptDraftItem(foundingSessionId,form.section,form.itemId);else if(form.action==='reject')await transport.rejectDraftItem(foundingSessionId,form.section,form.itemId);else if(form.action==='edit')await transport.updateDraftItem(foundingSessionId,form.section,form.itemId,form.name);else if(form.action==='add')await transport.addDraftItem(foundingSessionId,form.section,{id:form.itemId,name:form.name});else if(form.action==='explain'){const explanation=await transport.explainFoundingItem(foundingSessionId,form.section,form.itemId);notice=`${explanation.name}: ${explanation.rationale} Confidence ${Math.round(explanation.confidence*100)}%.`}return redirect(response,'/found')}
 if(request.method==='POST'&&request.url==='/found/refine'){assertLive();const form=await readForm(request);await transport.refineFoundingDraft(foundingSessionId,form.instruction);return redirect(response,'/found')}
 if(request.method==='POST'&&request.url==='/found/commit'){assertLive();const result=await transport.commitFoundingDraft(foundingSessionId,{actorId:'local-founder',permissions:['commit_company']});notice=`Your company has been created. ${result.capabilities.length} required capabilities, ${result.capabilities.filter(item=>item.state==='realised').length} realised, ${result.gaps.length} missing. Initial plan available.`;foundingSessionId=null;return redirect(response,'/')}
 if(request.method==='POST'&&request.url==='/actions/generate-plan')await transport.generatePlan(read('acme-with-support-definition.json'));
 else if(request.method==='POST'&&request.url==='/actions/apply'){const plan=await transport.getPlan();await transport.applyPlan({planId:plan.id,approvedChangeIds:plan.changes.map(change=>change.id),authorization:{actorId:'local-developer',permissions:['apply_plan']}})}
 else if(request.method==='POST'&&request.url==='/actions/cancel'){const plan=await transport.getPlan();await transport.cancelPlan({planId:plan.id,authorization:{actorId:'local-developer',permissions:['approve_plan']}})}
 else if(request.method==='POST'&&request.url==='/eve'){const body=await readBody(request);const result=await invokeEve(body.tool,body.input||{},transport);response.setHeader('Content-Type','application/json');return response.end(JSON.stringify({ok:true,result}))}
 const view=await loadOperatingView(transport),activeRoute=request.url?.split('?')[0].slice(1)||'home';response.statusCode=request.method==='POST'?303:200;if(request.method==='POST')response.setHeader('Location','/');response.setHeader('Content-Type','text/html; charset=utf-8');response.end(renderOperatingView(view,{transportName:mode,notice,activeRoute}));
 }catch(error){response.statusCode=502;response.setHeader('Content-Type','text/html; charset=utf-8');response.end(`<!doctype html><title>Runtime unavailable</title><main><h1>OmniSeed runtime unavailable</h1><p>${escapeHtml(error.message)}</p><p>Start <code>npm run runtime</code>, or use <code>npm run dev:fixtures</code>.</p></main>`)}}).listen(port,()=>console.log(`OmniSeed OS (${mode}) listening on http://localhost:${port}`));
async function readBody(request){const chunks=[];for await(const chunk of request)chunks.push(chunk);return JSON.parse(Buffer.concat(chunks).toString()||'{}')}
async function readForm(request){const chunks=[];for await(const chunk of request)chunks.push(chunk);return Object.fromEntries(new URLSearchParams(Buffer.concat(chunks).toString()))}
function redirect(response,location){response.writeHead(303,{Location:location});response.end()}
function assertLive(){if(mode!=='live')throw new Error('Founding commit requires LiveTransport; start npm run runtime and npm run dev')}
function escapeHtml(value){return String(value).replace(/[&<>]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[char]))}
