import http from 'node:http';import fs from 'node:fs';import {LiveTransport,FixtureTransport} from '../lib/omniseed/transport.mjs';import {loadOperatingView,renderOperatingView} from '../lib/ui/render.mjs';import {invokeEve} from '../lib/eve/index.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(`../fixtures/${name}`,import.meta.url)));const fixtureMode=process.env.OMNISEED_TRANSPORT==='fixture';const transport=fixtureMode?new FixtureTransport(read('startup.json')):new LiveTransport({baseUrl:process.env.OMNISEED_URL||'http://127.0.0.1:8787'});const port=Number(process.env.PORT||3000);
http.createServer(async(request,response)=>{try{
 if(request.method==='POST'&&request.url==='/actions/generate-plan')await transport.generatePlan(read('acme-with-support-definition.json'));
 else if(request.method==='POST'&&request.url==='/actions/apply'){const plan=await transport.getPlan();await transport.applyPlan({planId:plan.id,approvedChangeIds:plan.changes.map(change=>change.id),authorization:{actorId:'local-developer',permissions:['apply_plan']}})}
 else if(request.method==='POST'&&request.url==='/actions/cancel'){const plan=await transport.getPlan();await transport.cancelPlan({planId:plan.id,authorization:{actorId:'local-developer',permissions:['approve_plan']}})}
 else if(request.method==='POST'&&request.url==='/eve'){const body=await readBody(request);const result=await invokeEve(body.tool,body.input||{},transport);response.setHeader('Content-Type','application/json');return response.end(JSON.stringify({ok:true,result}))}
 const view=await loadOperatingView(transport);response.statusCode=request.method==='POST'?303:200;if(request.method==='POST')response.setHeader('Location','/');response.setHeader('Content-Type','text/html; charset=utf-8');response.end(renderOperatingView(view,{transportName:fixtureMode?'fixture':'live'}));
 }catch(error){response.statusCode=502;response.setHeader('Content-Type','application/json');response.end(JSON.stringify({ok:false,error:error.message}))}}).listen(port,()=>console.log(`OmniSeed OS (${fixtureMode?'fixture':'live'}) listening on http://localhost:${port}`));
async function readBody(request){const chunks=[];for await(const chunk of request)chunks.push(chunk);return JSON.parse(Buffer.concat(chunks).toString()||'{}')}
