export const LILY_OPERATIONAL_IDENTITY='company_steward';
export function lilyIdentity({displayName='Lily',voice='system',presentation={}}={}){return {actorId:LILY_OPERATIONAL_IDENTITY,displayName,voice,presentation}}
export async function createLilyTurn(utterance,transport){const available=await transport.discoverOperations('lily');const resolved=await transport.resolveIntent(utterance);const registered=new Set(available.map(item=>item.id));if(resolved.candidateOperations?.some(id=>!registered.has(id)))throw new Error('Lily proposed an unregistered operation');return {utterance,resolved,availableCapabilities:available,actor:LILY_OPERATIONAL_IDENTITY}}
export async function invokeLily(operationId,input,transport){const available=await transport.discoverOperations('lily'),operation=available.find(item=>item.id===operationId);if(!operation)throw new Error('Lily can only request registered capabilities');if(operation.mutation)throw new Error('Lily cannot bypass policy or authorization');if(operation.runtimeOperation.startsWith('present'))return presentation(operationId,input);const method=operation.runtimeOperation==='getCurrentPlan'?'getPlan':operation.runtimeOperation;return transport[method](...(operationId==='get_capability'?[input.id]:[]))}
function presentation(operationId,input={}){const routes={present_home:'/',present_company:'/company',present_capability:'/capabilities',present_plan:'/plan',present_observation:'/observe',present_finding:'/observe',present_evidence:'/observe',present_activity:'/activity',present_infrastructure:'/infrastructure'};return {operationId,route:routes[operationId],focusId:input.id||null,mutation:false}}

export class BrowserSpeechToTextProvider{constructor({Recognition=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition}={}){this.Recognition=Recognition}start({onTranscript,onState,onError}){if(!this.Recognition)throw new Error('Speech recognition is not supported by this browser');const recognition=new this.Recognition();recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>onState?.('listening');recognition.onresult=event=>{const transcript=[...event.results].map(item=>item[0].transcript).join('');onTranscript(transcript,event.results[event.results.length-1].isFinal)};recognition.onerror=event=>onError?.(event.error);recognition.start();return {stop:()=>recognition.stop()}}}
export class BrowserTextToSpeechProvider{speak(text,{onState}={}){if(!globalThis.speechSynthesis)throw new Error('Speech output is not supported by this browser');const utterance=new SpeechSynthesisUtterance(text);utterance.onstart=()=>onState?.('speaking');utterance.onend=()=>onState?.('idle');speechSynthesis.speak(utterance);return {stop:()=>speechSynthesis.cancel()}}}
export class VoiceSession{constructor({speechToText,textToSpeech,submit}){this.speechToText=speechToText;this.textToSpeech=textToSpeech;this.submit=submit;this.state='idle';this.transcript=''}setState(value){this.state=value;return value}start(){this.setState('listening');return this.speechToText.start({onState:value=>this.setState(value),onTranscript:async(text,final)=>{this.transcript=text;if(final){this.setState('thinking');const response=await this.submit(text);this.setState('presenting');return response}},onError:()=>this.setState('error')})}speak(text){return this.textToSpeech.speak(text,{onState:value=>this.setState(value)})}}
